# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Music-PlayTab
version:      0.05
version_from: 
installdirs:  site
requires:
    Getopt::Long:                  2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
